server:
  port: 10001
  servlet:
    path: /
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true #G压缩
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,application/x-css,text/css
    min-response-size: 10240 #10kb以下忽略

spring:
  profiles:
    include: shiro,option,db
  banner:
    charset: UTF-8
  application:
    name: shiro
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null
  transaction:
    rollback-on-commit-failure: true
  servlet:
    multipart:
      # 开启 multipart 上传功能
      enabled: true
      # 文件写入磁盘的阈值
      file-size-threshold: 2KB
      # 最大文件大小1G
      max-file-size: 1024MB
      # 最大请求大小1G
      max-request-size: 1024MB
  #静态映射
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${option.static}/
#    add-mappings: false #不要为我们工程中的资源文件建立映射
#  mvc:
#    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常


#log日志
logging:
  config: classpath:log4j2.yml

#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.jacques.shiro.pojo
  mapper-locations: classpath:/mapper/*Mapper.xml

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql









