server:
  port: 10001
  servlet:
    path: /
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true #G压缩
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,application/x-css,text/css
    min-response-size: 10240 #10kb以下忽略
spring:
  banner:
    charset: UTF-8
  application:
    name: shiro
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/common?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    database: 2
    port: 6379
  transaction:
    rollback-on-commit-failure: true
logging:
  config: classpath:log4j2.yml
mybatis:
  configuration:
    map-underscore-to-camel-case: true

custom:
  md5Salt: qweqweqw
  redisExpire: 7200

#自定义设置
option:
  filePath: D:/static/file/ #文件存放地址
  fileUrl: /file/ #网页url前缀


